spring:
  config:
    import: optional:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3306/${db.name}?serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.generate_statistics: true
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}


  kafka:
    bootstrap-servers: ${kafka.url}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: delivery-update-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: record
    properties:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    topic:
      payment-topic: payment-event
      stock-restore-topic: stock-restore-event

delivery:
  api:
    base-url: ${delivery.url}
    uri: ${delivery.uri}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug

server:
  port: 8080

jwt:
  secret:
    key: ${jwt.secret.key}

kakao:
  token: ${kakao.accesstoken}
  url: ${kakao.url}

payment:
  toss:
    test-client-key: ${payment.toss.test-client-key}
    test-secret-key: ${payment.toss.test-secret-key}
    confirm-uri: ${payment.toss.confirm-uri}
    cancel-uri: ${payment.toss.cancel-uri}
